# Generated by Django 3.0.8 on 2020-08-05 13:46

from django.db import migrations, models
import embed_video.fields


class Migration(migrations.Migration):

    dependencies = [
        ('answers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Item12',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video12', embed_video.fields.EmbedVideoField()),
            ],
        ),
        migrations.CreateModel(
            name='Item6',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video6', embed_video.fields.EmbedVideoField()),
            ],
        ),
        migrations.RenameModel(
            old_name='Item',
            new_name='Item10',
        ),
        migrations.RenameModel(
            old_name='Item1',
            new_name='Item11',
        ),
        migrations.RenameField(
            model_name='item10',
            old_name='video',
            new_name='video10',
        ),
        migrations.RenameField(
            model_name='item11',
            old_name='video1',
            new_name='video11',
        ),
    ]
