# Generated by Django 3.0.8 on 2020-08-06 06:17

from django.db import migrations, models
import embed_video.fields


class Migration(migrations.Migration):

    dependencies = [
        ('answers', '0002_auto_20200805_1916'),
    ]

    operations = [
        migrations.CreateModel(
            name='Item7',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video7', embed_video.fields.EmbedVideoField()),
            ],
        ),
        migrations.CreateModel(
            name='Item8',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video8', embed_video.fields.EmbedVideoField()),
            ],
        ),
        migrations.CreateModel(
            name='Item9',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video9', embed_video.fields.EmbedVideoField()),
            ],
        ),
    ]
